server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}
  servlet:
    context-path: /registroConsignatario
spring:
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
