server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}
  servlet:
    context-path: /consigneeRegistration
spring:
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
logging:
  level:
    org:
      hibernate:
        SQL: debug
