-- countries --
INSERT INTO `country` (id,code_country,name,created_at) VALUES (1, 1, 'AFGANISTÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (2, 2, 'ALBANIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (3, 3, 'ALEMANIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (4, 4, 'ANDORRA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (5, 5, 'ANGOLA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (6, 6, 'ANTIGUA Y BARBUDA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (7, 7, 'ARABIA SAUDITA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (8, 8, 'ARGELIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (9, 9, 'ARGENTINA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (10, 10, 'ARMENIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (11, 11, 'AUSTRALIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (12, 12, 'AUSTRIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (13, 13, 'AZERBAIYÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (14, 14, 'BAHAMAS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (15, 15, 'BAHREIN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (16, 16, 'BANGLADESH', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (17, 17, 'BARBADOS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (18, 18, 'BIELORRUSIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (19, 19, 'BELICE', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (20, 20, 'BENIN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (21, 21, 'BUTÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (22, 22, 'BOLIVIA (ESTADO PLURINACIONAL DE)', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (23, 23, 'BOSNIA Y HERZEGOVINA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (24, 24, 'BOTSUANA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (25, 25, 'BRASIL', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (26, 26, 'BRUNEI DARUSSALAM', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (27, 27, 'BULGARIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (28, 28, 'BURKINA FASO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (29, 29, 'BURUNDI', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (30, 30, 'BÉLGICA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (31, 31, 'CABO VERDE', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (32, 32, 'CAMBOYA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (33, 33, 'CAMERÚN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (34, 34, 'CANADÁ', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (35, 35, 'CHAD', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (36, 36, 'CHEQUIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (37, 37, 'CHILE', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (38, 38, 'CHINA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (39, 39, 'CHIPRE', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (40, 40, 'COLOMBIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (41, 41, 'COMORAS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (42, 42, 'CONGO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (43, 43, 'COSTA RICA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (44, 44, 'CROACIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (45, 45, 'CUBA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (46, 46, 'COSTA DE MARFIL', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (47, 47, 'DINAMARCA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (48, 48, 'DJIBOUTI', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (49, 49, 'DOMINICA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (50, 50, 'ECUADOR', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (51, 51, 'EGIPTO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (52, 52, 'EL SALVADOR', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (53, 53, 'EMIRATOS ÁRABES UNIDOS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (54, 54, 'ERITREA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (55, 55, 'ESLOVAQUIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (56, 56, 'ESLOVENIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (57, 57, 'ESPAÑA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (58, 58, 'ESTADOS UNIDOS DE AMÉRICA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (59, 59, 'ESTONIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (60, 60, 'ETIOPÍA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (61, 61, 'FEDERACIÓN DE RUSIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (62, 62, 'FIYI', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (63, 63, 'FILIPINAS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (64, 64, 'FINLANDIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (65, 65, 'FRANCIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (66, 66, 'GABÓN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (67, 67, 'GAMBIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (68, 68, 'GEORGIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (69, 69, 'GHANA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (70, 70, 'GRANADA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (71, 71, 'GRECIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (72, 72, 'GUATEMALA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (73, 73, 'GUINEA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (74, 74, 'GUINEA ECUATORIAL', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (75, 75, 'GUINEA-BISSAU', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (76, 76, 'GUYANA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (77, 77, 'HAITÍ', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (78, 78, 'HONDURAS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (79, 79, 'HUNGRÍA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (80, 80, 'INDIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (81, 81, 'INDONESIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (82, 82, 'IRAQ', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (83, 83, 'IRLANDA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (84, 84, 'IRÁN (REPÚBLICA ISLÁMICA DE)', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (85, 85, 'ISLANDIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (86, 86, 'ISLAS COOK', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (87, 87, 'ISLAS FEROE (MIEMBRO ASOCIADO)', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (88, 88, 'ISLAS MARSHALL', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (89, 89, 'ISLAS SALOMÓN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (90, 90, 'ISRAEL', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (91, 91, 'ITALIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (92, 92, 'JAMAICA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (93, 93, 'JAPÓN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (94, 94, 'JORDANIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (95, 95, 'KAZAJISTÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (96, 96, 'KENIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (97, 97, 'KIRGUISTÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (98, 98, 'KIRIBATI', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (99, 99, 'KUWAIT', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (100, 100, 'LESOTO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (101, 101, 'LETONIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (102, 102, 'LIBERIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (103, 103, 'LIBIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (104, 104, 'LITUANIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (105, 105, 'LUXEMBURGO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (106, 106, 'LÍBANO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (107, 107, 'MADAGASCAR', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (108, 108, 'MALASIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (109, 109, 'MALAWI', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (110, 110, 'MALDIVAS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (111, 111, 'MALTA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (112, 112, 'MALÍ', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (113, 113, 'MARRUECOS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (114, 114, 'MAURICIO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (115, 115, 'MAURITANIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (116, 116, 'MICRONESIA (ESTADOS FEDERADOS DE)', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (117, 117, 'MONGOLIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (118, 118, 'MONTENEGRO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (119, 119, 'MOZAMBIQUE', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (120, 120, 'MYANMAR', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (121, 121, 'MÉXICO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (122, 122, 'MÓNACO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (123, 123, 'NAMIBIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (124, 124, 'NAURU', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (125, 125, 'NEPAL', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (126, 126, 'NICARAGUA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (127, 127, 'NIGERIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (128, 128, 'NIUE', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (129, 129, 'NORUEGA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (130, 130, 'NUEVA ZELANDA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (131, 131, 'NÍGER', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (132, 132, 'OMÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (133, 133, 'PAKISTÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (134, 134, 'PALAOS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (135, 135, 'PANAMÁ', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (136, 136, 'PAPUA NUEVA GUINEA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (137, 137, 'PARAGUAY', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (138, 138, 'PAÍSES BAJOS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (139, 139, 'PERÚ', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (140, 140, 'POLONIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (141, 141, 'PORTUGAL', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (142, 142, 'QATAR', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (143, 143, 'REINO UNIDO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (144, 144, 'REPÚBLICA CENTROAFRICANA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (145, 145, 'REPÚBLICA DEMOCRÁTICA POPULAR LAO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (146, 146, 'REPÚBLICA DEMOCRÁTICA DEL CONGO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (147, 147, 'REPÚBLICA DOMINICANA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (148, 148, 'REPÚBLICA POPULAR DEMOCRÁTICA DE COREA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (149, 149, 'REPÚBLICA UNIDA DE TANZANÍA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (150, 150, 'REPÚBLICA DE COREA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (151, 151, 'REPÚBLICA DE MOLDAVIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (152, 152, 'REPÚBLICA ÁRABE SIRIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (153, 153, 'RUMANIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (154, 154, 'REPÚBLICA DE RUANDA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (155, 155, 'SAN CRISTÓBAL Y NIEVES', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (156, 156, 'SAMOA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (157, 157, 'SAN MARINO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (158, 158, 'SAN VICENTE Y LAS GRANADINAS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (159, 159, 'SANTA LUCÍA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (160, 160, 'SANTO TOMÉ Y PRÍNCIPE', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (161, 161, 'SENEGAL', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (162, 162, 'SERBIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (163, 163, 'SEYCHELLES', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (164, 164, 'SIERRA LEONA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (165, 165, 'SINGAPUR', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (166, 166, 'SOMALIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (167, 167, 'SRI LANKA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (168, 168, 'SUDÁFRICA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (169, 169, 'SUDÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (170, 170, 'SUDÁN DEL SUR', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (171, 171, 'SUECIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (172, 172, 'SUIZA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (173, 173, 'SURINAM', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (174, 174, 'SUAZILANDIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (175, 175, 'TAILANDIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (176, 176, 'TAYIKISTÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (177, 177, 'TIMOR ORIENTAL', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (178, 178, 'TOGO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (179, 179, 'TOKELAU', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (180, 180, 'TONGA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (181, 181, 'TRINIDAD Y TOBAGO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (182, 182, 'TURKMENISTÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (183, 183, 'TURQUÍA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (184, 184, 'TUVALU', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (185, 185, 'TÚNEZ', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (186, 186, 'UCRANIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (187, 187, 'UGANDA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (188, 188, 'URUGUAY', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (189, 189, 'UZBEKISTÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (190, 190, 'VANUATU', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (191, 191, 'VENEZUELA (REPÚBLICA BOLIVARIANA DE)', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (192, 192, 'VIETNAM', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (193, 193, 'YEMEN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (194, 194, 'ZAMBIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (195, 195, 'ZIMBABUE', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (196, 196, 'REPÚBLICA DE MACEDONIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (197, 197, 'NO REGISTRADO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (198, 198, 'ANTILLAS NEERLANDESAS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (199, 199, 'ARUBA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (200, 200, 'BERMUDAS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (201, 201, 'ISLAS CAIMÁN', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (202, 202, 'GROENLANDIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (203, 203, 'ISLAS MALVINAS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (204, 204, 'YUGOSLAVIA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (205, 205, 'PUERTO RICO', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (206, 206, 'HONG KONG', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (207, 207, 'FORMOSA', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (208, 208, 'NO ESPECIFICOS', CURRENT_TIMESTAMP);
INSERT INTO `country` (id,code_country,name,created_at) VALUES (209, 209, 'ISLAS VIRGENES BRITANICAS', CURRENT_TIMESTAMP);

-- Document Types --
INSERT INTO `document_type` (id,code_document,name,description) VALUES (1,'CINAL','CI-CARNET DE IDENTIDAD','Documentos de identidad definidos por el SIN');
INSERT INTO `document_type` (id,code_document,name,description) VALUES (2,'CIEXT','CEX-CARNET DE IDENTIDAD DE EXTRANJERO','Documentos de identidad definidos por el SIN');
INSERT INTO `document_type` (id,code_document,name,description) VALUES (3,'PASAP','PAS-PASAPORTE','Documentos de identidad definidos por el SIN');
INSERT INTO `document_type` (id,code_document,name,description) VALUES (4,'OTRO','OD-OTRO DOCUMENTO DE IDENTIDAD','Documentos de identidad definidos por el SIN');
INSERT INTO `document_type` (id,code_document,name,description) VALUES (5,'NIT','NIT-NUMERO DE IDENTIFICACION TRIBUTARIA','Documentos de identidad definidos por el SIN');
